### ISSUE TITLE
Breach crime atttack

### ISSUE THREAD

**Issue by darasat** [gios/gzipper#102]
Hi good day Gios.

Congratulations for this great package.

I have a question.. I want to know if this tool generate the files having in count a  Breach crime atttack, how we can host files without compromise the security. 

https://stackoverflow.com/questions/30266931/gzip-compression-on-https-traffic-security-issue-with-breach-crime-attack#comment48643009_30266931

Thank you very much.

Best Regards,
Diego R.

**Comment by gios** [comment]
Hey @darasat , Under the hood gzipper uses built-in compression modules from Nodejs. It should be safe in using files that were generated by this library, but network protection has to be done on  your side, I suppose.
