### ISSUE TITLE
Can't turn off logs completely

### ISSUE THREAD

**Issue by coldfeudal** [gios/gzipper#107]
Basically there is no silent argument or something like that, so this part always fires
```js
// In src/Compress.ts
Logger.log(
  `${filesCount} ${
    filesCount > 1 ? 'files have' : 'file has'
  } been compressed. (${Helpers.readableHrtime(hrtime)})`,
  LogLevel.SUCCESS,
);
```
Is there any way to make it work or sould there be a switch? Expecting something like `silent: true`

**Comment by gios** [comment]
Hey @coldfeudal, What about logging only errors with `--verbose`? This part won't be fired when this flag is not set.

**Comment by gios** [comment]
A new version v8 has been published
