### ISSUE TITLE
Feature Request: Exclude certain file types

### ISSUE THREAD

**Issue by jamesbarrett95** [gios/gzipper#15]
Hello,

I think it would be great to have a feature where you can exclude particular file types.

An example command might be `gzipper ./dist --exclude=json`

Thanks!

**Comment by gios** [comment]
@jamesbarrett95 Hi thanks for your proposal, I will take a look.

**Comment by gios** [comment]
@jamesbarrett95 I have deployed a new version to npm v2.7.0 with this functionality.
Usage:
`gzipper ./dist --exclude=json,jpeg,jpg`
