### ISSUE TITLE
Proposal - add a CLI flag to filter file extensions

### ISSUE THREAD

**Issue by kubk** [gios/gzipper#17]
Hi, thanks for the library. Gzipper already supports `--exclude` option for excluding file extensions from compression, which is great. It would be nice to also have `--include` option for filtering file extensions. It will allow to use `gzipper --include=html,js,css` instead of `gzipper --exclude=txt,ttf,eot,woff,woff2,svg,jpg,png...`

Can make a PR.

**Comment by gios** [comment]
@kubk cool, I am looking forward to your PR.
P.S don't forget to write an additional test for this functionality similar to `--exclude`.

**Comment by gios** [comment]
@kubk New version [v2.8.0](https://www.npmjs.com/package/gzipper) has been deployed to npm.
