### ISSUE TITLE
Output file same as original

### ISSUE THREAD

**Issue by daviddsingleton** [gios/gzipper#18]
Compressing a file to overwrite the original for quick S3 uploads of HTML / JS / CSS overwrites the file before reading it, causing gzipper to zip up an empty file.

When serving a website via S3, you upload the file with the original extension and just put the content encoding as gzip, in this instance gzipper does not work because it creates the new file first, rather than compressing in memory.

**Comment by sebastienfi** [comment]
Use `outputPath` to write to another dir.

`gzipper --output-file-format [filename].[ext] ./build ./build-compressed && aws s3 sync --acl public-read --content-encoding 'gzip' ./build-compressed s3://{your-bucket}/ --delete`
