### ISSUE TITLE
How to use with Angular7, Ionic 4 

### ISSUE THREAD

**Issue by ayoubkhan558** [gios/gzipper#21]
How to use ith Angular7, Ionic 4

**Comment by 2advancesolutions** [comment]
Is this issue fix been yet?

**Comment by 4dagio** [comment]
Has anyone found the solution?

**Comment by elwinschmitz** [comment]
I'm able to use it, so what is the exact issue?

I use it in a "post-build"-step, so my `package.json` looks like:

```json
{
  "scripts": {
    "build": "ng build --prod",
    "postbuild": "npm run compress:gzip && npm run compress:brotli",
    "compress:gzip": "gzipper compress --skip-compressed --remove-larger --level 9 ./www/",
    "compress:brotli": "gzipper compress --skip-compressed --remove-larger --brotli ./www/",
  }
}
```

Every time you run `npm run build` all the scripts are run in order (`npm` handles scripts named "`post*"` and "`pre*"` automatically).

Ionic uses the `www`-folder by default as the output of the build, so these files need to be compressed. (This is maybe different from the default location used by `gzipper`)
