### ISSUE TITLE
Add option for threshold / minFileSize

### ISSUE THREAD

**Issue by florian-g-** [gios/gzipper#22]
**Feature request**
Thank you for this very useful project!
It would be great to add an option to exclude files below a certain threshold, e.g. only compress files larger than 200 bytes.
More or less the same feature as offered by brotli-webpack-plugin.

I guess it can be implemented easily here:
https://github.com/gios/gzipper/blob/master/src/Gzipper.js

If you do not have this on your roadmap anyway, I could provide a PR, if you are interested?

**Comment by gios** [comment]
@florian-g- Hi, It would be great to implement this feature. Currently I don't have a exact roadmap but I have a plan to do it soon.

**Comment by gios** [comment]
@florian-g- New version has been published [v2.10.0](https://www.npmjs.com/package/gzipper).
