### ISSUE TITLE
--output-file-format for all files in the build folder

### ISSUE THREAD

**Issue by Nywlem** [gios/gzipper#26]
Is it possible to use the option --output-file-format on a folder to read all the files with its formats.

eg:  "build": "react-scripts build && gzipper -v --output-file-format 'build/*.*' ./build ./gzipped",

**Comment by gios** [comment]
@Nywlem If I correctly understand you want to leave the original files format after gzipping. You could do this using this option `react-scripts build && gzipper -v --output-file-format '[filename].[ext]' ./build ./gzipped`.
--output-file-format iterates over all files in each folder, change their representation and can't be applied to folders.

example:
a.js -> --output-file-format test-[filename]-[hash].[ext].[compressExt] -> test-a-c9aa4d55-ca1f-4118.js.gz

I am going to add more examples soon.
