### ISSUE TITLE
Setting gzip level doesn't work

### ISSUE THREAD

**Issue by strmer15** [gios/gzipper#29]
If you run the gzipper CLI with npx, using the `-gl` option seems to have no effect.

`npx gzipper -gl 9 build/static/js/`

`gzipper: GZIP -> gzipLevel: NaN, gzipMemoryLevel: NaN, gzipStrategy: NaN`

If you use the `--gzip-level` option, the option is put into the output.

`npx gzipper --gzip-level 9 build/static/js/`

`gzipper: GZIP -> gzipLevel: 9, gzipMemoryLevel: NaN, gzipStrategy: NaN`

However, setting `--gzip-level 1` and `--gzip-level 9` does not change the size of the file output - when I run the `gzip` command in bash with `-1` vs. `-9` on the same files, it makes a fairly large difference.

Looking at the zlib docs for NPM - https://nodejs.org/api/zlib.html#zlib_class_options - it seems that the options needing to be set are `level`, `memLevel`, and `strategy`, but looking at the source for this library, they're being set to `gzipLevel`, `gzipMemoryLevel`, and `gzipStrategy`, so they're not taking effect.

**Comment by gios** [comment]
@strmer15 Thank you fro your issues, tt's a command module regression. I am going to cover additional functionality and roll out the fix soon.

**Comment by gios** [comment]
@strmer15 Version 3.2.0 has been published.

**Comment by strmer15** [comment]
Thanks @gios!

**Comment by strmer15** [comment]
Actually, when I tested this out, it still doesn't work.  The options being passed to zlib never changed in 3.2.0, so the gzip level / memory level / strategy didn't work for me in local dev (gzipper took them in correctly but never applied them during compression).

In addition, the commander documentation tells why the `-gl` option doesn't work and the `--gzip-level` option does work: `Each option can have a short flag (single character) and a long name` (https://github.com/tj/commander.js#options).  So, if your short option is not a single character, it's not going to work.

I'll create a pull request to actually fix this and remove the short options that don't actually work.
