### ISSUE TITLE
Brotli quality default not correct

### ISSUE THREAD

**Issue by strmer15** [gios/gzipper#30]
If I run gzipper using npx to do brotli compression:

`npx gzipper --brotli build/static/js/`

My files are compressed, but the size is larger than my gzipped files.  The documentation states that the default for `--brotli-quality` is `11`, but it doesn't seem to work that way.  If I explicitly put `--brotli-quality 11` on the command line, it then compresses smaller than my gzipped files and seems to work correctly.

`npx gzipper --brotli --brotli-quality 11 build/static/js/`

**Comment by gios** [comment]
@strmer15 Version 3.2.0 has been published.
npx gzipper --brotli --brotli-quality 1
![image](https://user-images.githubusercontent.com/6967294/66705465-a04a9900-ed2f-11e9-9e59-5c47900c428e.png)
npx gzipper --brotli --brotli-quality 11 or npx gzipper --brotli
![image](https://user-images.githubusercontent.com/6967294/66705454-8e68f600-ed2f-11e9-9cac-80d0e11f3a1b.png)
