### ISSUE TITLE
zip files not working 

### ISSUE THREAD

**Issue by jayshree138** [gios/gzipper#32]
Hi,  I am trying to use gzipper page and when I run "ng build && gzipper --verbose ./dist" command, it creates all files with gz extension , but after ng  serve , my server still using uncompressed files. Please suggest where I have to define content-type as gzip for main.ts pollyfills... etc files.
Thanks!

**Comment by freed00m** [comment]
This is not how 'ng serve' works.
Ng serve is not serving the files in /dist directory.

However I am not sure if making it work with ng serve.
