### ISSUE TITLE
Error: Can't find a path

### ISSUE THREAD

**Issue by sunaina2084** [gios/gzipper#39]
When I try to run gzipper in my project I get **Error: Can't find a path**. The same error we can see on runkit - https://npm.runkit.com/gzipper 

![image](https://user-images.githubusercontent.com/28888272/68487637-73739e00-0269-11ea-90e6-e95527004e77.png)

Can I please get a help?

**Comment by gios** [comment]
@sunaina2084 Are you using this package as a node.js module? I am asking because right now this package works only from CLI. If Yes I will create a PR to fix this out.

**Comment by sunaina2084** [comment]
@gios  yes, I am using gzipper as npm/node module in my angular 7 project. It could install gzipper correctly. But running it have that error I mentioned. Thank you for looking into it.
