### ISSUE TITLE
add compression settings

### ISSUE THREAD

**Issue by nosovk** [gios/gzipper#4]
Could you please add compression settings support?
For example reading settings from package.json
1. Gzip settings could be exposed, at least compression lvevl
2. optional use of brotli would be nice

Settings could be stored in package.json or in separate .json, or in env...

**Comment by gios** [comment]
@nosovk Good suggestion, I will check it out as soon as possible.

**Comment by gios** [comment]
@nosovk Brotli, additional compression options and .env variables will be added in #6 **2.2.0**.
