### ISSUE TITLE
Can gzipper be used on a single file?

### ISSUE THREAD

**Issue by mischuler** [gios/gzipper#42]
**Help wanted**

The documentation seems to indicate I can only zip on a directory.

I'd ideally like to only do this on a single file so I don't need to create any sub-directories. Did I miss something in the README or is this an unsupported feature right now?

Thanks.

**Comment by gios** [comment]
Hi @mischuler , 
It's an unsupported feature but I will take a look and roll out a PR with changes soon.
Thanks for your request.

**Comment by mischuler** [comment]
@gios 

Appreciate the feedback and quick response. I'll be on the lookout and I'll be more than happy to test it for you.
