### ISSUE TITLE
Font files are not compressed by default

### ISSUE THREAD

**Issue by Mustahsan1** [gios/gzipper#57]
Hi,

I am using Gzipper for compressing my build files, but it looks like it ignores font files with extensions (ttf,woff,woff2, eot) by default. I am using this command to compress:

`gzipper --verbose ./dist ./compressed`

i have to explicitly define formats in --include option:

`gzipper --verbose ./dist ./compressed --include ttf,woff2,woff,txt,svg,json,png,jpg,jpeg,gif,js,html,css,scss,eot,ico`

Shouldn't it be better if it compress all file formats by default?

**Comment by gios** [comment]
Hi @Mustahsan1 
Which version do you use? Previous versions have a hard-coded list of extensions to compress. I would recommend using version >= 3.6.1.

**Comment by Mustahsan1** [comment]
Sorry I was using 3.4.x version. updating to latest fixed the problem.

Thanks for your time
