### ISSUE TITLE
Include don't work for multiple extensions

### ISSUE THREAD

**Issue by HDeiro** [gios/gzipper#61]
I'm trying to compress some files generated from an angular build.

![image](https://user-images.githubusercontent.com/6384551/90462230-c3c43a00-e0de-11ea-9f84-b728a1618c85.png)

Seems like in the version 4.0.1 the --include option is not working very well for multiple extensions.

**Comment by gios** [comment]
Hi @HDeiro 

Could you please send a folder structure where you run gzipper command?
I have tested this scenario manually and it works fine, test passed too.

**Comment by HDeiro** [comment]
@gios, it's the generated dist folder for an angular build.

it basically had:

```
/dist
    some-javascripts.js
    some-css.css
    some-html.html
    /assets
        other files
```

**Comment by HarieswaranD** [comment]
I am too facing the same issue. Exclude also not working in my case

**Comment by gios** [comment]
@HarieswaranD Which OS are you using because I can't reproduce it on a Linux-like environment (use WSL under Windows)? Node and gzipper version also would be helpful.
BTW I published a new version _v4.5.0_ with updated commander and some other packages, hope it will help.

**Comment by HarieswaranD** [comment]
I am using a Windows machine. Windows 10 Enterprise.
