### ISSUE TITLE
gzipper: command not found

### ISSUE THREAD

**Issue by galeej** [gios/gzipper#71]
Hi,

I am getting "gzipper: command not found" when i run any gzipper command.

I had installed it using the following command:
npm i gzipper -g

The result shows that the package was installed but i am unable to call any of the gzipper commands (even gzipper --help)

Kindly let me know how to fix this

**Comment by gios** [comment]
@galeej Hi, Does this happen with gzipper only or with all packages?
Try to add npm `bin` folder to PATH from this issue https://github.com/preactjs/preact-cli/issues/487. 
`export PATH=$PATH:~/.npm-packages/bin`
