### ISSUE TITLE
Change in output name format

### ISSUE THREAD

**Issue by subodhkumar** [gios/gzipper#8]
Hi,

Just wanted to check if we have any option currently to change the output format. 

For example, 
The current output format is
[filename].[filetype].gz
can we have an output of the format like 
[filename].[gz].[filetype]

If so, shall i make a pull request. Please confirm

**Comment by gios** [comment]
@subodhkumar Hi,
Unfortunately, we don't have this functionality and can't edit the output format. Every contribution is appreciated if you have time to add an additional option like --otputFormat=[filename].[gz].[filetype] it will be great. Otherwise, I can add this option on this weekends.

**Comment by gios** [comment]
I've published a new version v2.5.0 with changes regarding output file format. Please take a look and give feedback if something else is necessary.

**Comment by subodhkumar** [comment]
@gios awesome...!! i was about to push my changes and saw your changes while pushing...
Thanks man!
