### ISSUE TITLE
file without extension will have some wrong

### ISSUE THREAD

**Issue by dwhmofly** [gios/gzipper#95]
the comressed file extension will be "..br" (brotli)
use --output-file-format [filename].[compressExt].[ext] will be ".br."

Is it possible to add a option [ext?] and use --output-file-format [filename].[compressExt][ext?] will be ".br"(without extension) or ".br.xx" (with extension)

**Comment by gios** [comment]
Hello, can you try to use `--output-file-format [filename].[compressExt]` instead \?

**Comment by gios** [comment]
You can try to test latest v8.0.0. This issue might have been fixed in this release.
